import './globals.css'
import Navbar from './components/Navbar'
import BG from "./images/download.jpg"
import { Metadata } from 'next'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: "AJDev Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className='max-w-[1150px] mx-auto justify-center'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
