import './globals.css'
import Navbar from './components/Navbar'
import BG from "./images/download.jpg"
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: "AJDev Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='max-w-[1150px] h-[100vh] mx-auto bg-gradient-to-t from-gray-500 bg-fixed'>
        {/* <Navbar /> */}
          {children}
      </body>
    </html>
  )
}
